chore: update repo-metadata.json
googleapis/nodejs-grafeas pull request #321
Opened 2022-01-14 21:14 UTC by averikitsch

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/nodejs-grafeas/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

2022-01-17 17:40 UTC, bcoe requested changes
This is another weird one, where the product team asked us to call the library `grafeas`, but the name of the API we interact with is `containeranalysis`.

Rather than removing the `api_shortname` field, if you instead update it to be `containeranalysis`, the checks should start passing.

2022-01-17 17:41 UTC, bcoe commented
I double checked, and this agrees with what .NET did:

https://github.com/googleapis/google-cloud-dotnet/blob/main/apis/Grafeas.V1/.repo-metadata.json#L6

2022-02-03 19:59 UTC, averikitsch commented
ping @bcoe

2022-02-05 16:41 UTC, bcoe approved these changes

2022-02-07 17:04 UTC, merged